services:
  postgres_eshop:
    image: postgres:latest
    container_name: postgres_eshop
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: CatalogDb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

