services:
  catalogdb:
    image: postgres:latest
    container_name: catalogdb
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: CatalogDb
    volumes:
      - catalogdb_data:/var/lib/postgresql/data
   
  basketdb:
    image: postgres:latest
    container_name: basketdb
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: BasketDb
    volumes:
      - basketdb_data:/var/lib/postgresql/data
   
  basketRedis:
    image: redis:latest
    ports:
      - "6382:6379"
    volumes:
      - "basketRedis-data:/data"

volumes:
  catalogdb_data:
  basketdb_data:
  basketRedis-data:

