services:
  basketdb:
    image: postgres:latest
    container_name: basketdb
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: BasketDb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
