services:
  catalogdb:
    image: postgres:latest
    container_name: catalogdb
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: CatalogDb
    volumes:
      - catalogdb_data:/var/lib/postgresql/data
   
  basketdb:
    image: postgres:latest
    container_name: basketdb
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: BasketDb
    volumes:
      - basketdb_data:/var/lib/postgresql/data
   
  basketRedis:
    image: redis:latest
    ports:
      - "6382:6379"
    volumes:
      - "basketRedis-data:/data"

  discountdb:
    image: postgres:latest
    container_name: discountdb
    restart: unless-stopped
    ports:
      - "5438:5432"
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: DiscountDb
        PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - discountdb_data:/var/lib/postgresql/data
        
  orderdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: orderdb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SwN12345678
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - orderdb_data:/var/opt/mssql
        
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: ecommerce-mq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  catalogdb_data:
  basketdb_data:
  basketRedis-data:
  discountdb_data:
  orderdb_data:


